In [6]:
# --NUMPY BÖLÜMÜ--
# 1.Numpy İle Matris İşlemleri 

import numpy as np
import pandas as pd
np.random.seed(10)
M1 = np.random.randint(0,101, size = (5,5))


sapma = np.std(M1)
ort = np.mean(M1)
vary = np.var(M1)


sol_ust     = M1[0, 0] 
sol_alt     = M1[-1, 0]
sag_ust     = M1[0, -1]
sag_alt     = M1[-1, -1]


birinci_kosegen = np.diagonal(M1)
ikinci_kosegen = np.fliplr(M1).diagonal()  # Ayna görüntüsü alıyor bu yüzden diagonal kodu eklenir 



print("MATRİS:\n",M1)
print("Standart sapma : ",sapma)
print("Ortalama: ",ort)
print("Varyans : ",vary)
print("En Küçük Değer: " , M1.min())
print("En Büyük Değer: " , M1.max())
print("Sol Üst : ",sol_ust)
print("Sol Alt : ",sol_alt)
print("Sag Üst : ",sag_ust)
print("Sag Alt : ",sag_alt)
print("Birinci Köşegen : ",birinci_kosegen)
print("İkinci Köşegen : ",ikinci_kosegen)
print("İki köşegenin toplamı:", birinci_kosegen.sum() + ikinci_kosegen.sum())


MATRİS:
 [[  9 100  15  64  28]
 [ 89  93  29   8  73]
 [  0  40  36  16 100]
 [ 11  54  88  62  33]
 [ 72 100  78  49  51]]
Standart sapma :  32.08354095170918
Ortalama:  51.92
Varyans :  1029.3536
En Küçük Değer:  0
En Büyük Değer:  100
Sol Üst :  9
Sol Alt :  72
Sag Üst :  28
Sag Alt :  51
Birinci Köşegen :  [ 9 93 36 62 51]
İkinci Köşegen :  [28  8 36 54 72]
İki köşegenin toplamı: 449


In [7]:
# 2.Numpy İle Veri Simülasyonu

np.random.seed(10)
puanlar=np.random.normal(loc=75,scale=15,size=1000).astype(int)
kırpılmıs_puanlar=np.clip(puanlar,0,100)
ort=np.mean(puanlar)
medyan=np.median(puanlar)
sapma=np.std(puanlar)
dusuk_puanlar=np.sum(puanlar<50)
print("Puan Listesi\n  ",kırpılmıs_puanlar)
print("Ortalama: ",ort)
print("Medyan:",medyan)
print("Standart Sapma: ",sapma)
print("50 den Düşük Öğrenci Sayısı ",dusuk_puanlar)

Puan Listesi
   [ 94  85  51  74  84  64  78  76  75  72  81  93  60  90  78  81  57  77
  97  58  45  48  78 100  91 100  76  95  70  84  70  66  76  67  94  77
  81  69  93  64  84  69  60  67  62  71  69  79  83  72  74  79  66  85
  87  78 100  88  73  69  71  67  91  64  73  67  90  53  69  73  79  81
  71  89  79 100  52  84  59  63 100 100  47  71  74  43  74  80  78  45
  91  78  74  63  85  88  67  76  87  45  76  46  61  82  72  68  70  87
  85  63  79  67 100  63  70  69  68  77  79  50  66  55  93 100  95  80
  90  77  99  85  71  58  65  79  56  71  95  75 100  96  70  54  74  67
  80  99  58  69  79  92  82  81  95  82  71  75  64  83  89  30  93  74
  81  84  40  57  70  63  79  67  49  84  91  83  64  71  83  84  90  70
  53  64  83  86 100  76  78  72  68  86  80  71  58  73  69  93  89  59
  92  66  76  93  59  77  58  45  89  75  62  51  68  95  81  69  64  76
  51  95  82  92  66  87  85  52  77  79  66  69  81  74  59  83  78  78
  76  81  70  62  63  91  44  83  5

In [11]:
# --PANDAS BÖLÜMÜ--
isim=['Ali','Ayşe','Mehmet','Zeynep','Ahmet']
yas=[20,21,19,22,20]
bolum=['Bilgisayar','Fizik','Kimya','Bilgisayar','Fizik']
mat_notlar=[70,60,80,90,55]
fiz_notlar=[65,75,70,85,60]
kim_notlar=[80,85,65,95,70]

dframe=pd.DataFrame({'ÖĞRENCİ':isim,'YAŞ':yas,'BÖLÜM':bolum,'MATEMATİK':mat_notlar,'FİZİK':fiz_notlar,'KİMYA':kim_notlar})

dframe["ORTALAMA"] = dframe[["MATEMATİK", "FİZİK", "KİMYA"]].mean(axis=1).astype(int)
dframe



ÖĞRENCİ  YAŞ       BÖLÜM  MATEMATİK  FİZİK  KİMYA  ORTALAMA
0     Ali   20  Bilgisayar         70     65     80        71
1    Ayşe   21       Fizik         60     75     85        73
2  Mehmet   19       Kimya         80     70     65        71
3  Zeynep   22  Bilgisayar         90     85     95        90
4   Ahmet   20       Fizik         55     60     70        61

In [10]:
#--GÖREVLER--
ort_mat=sum(mat_notlar) / len(mat_notlar)
ort_fiz=sum(fiz_notlar) / len(fiz_notlar)
ort_kim=sum(kim_notlar) / len(kim_notlar)
mat_max = dframe["MATEMATİK"].max()
ogrenci = dframe[dframe["MATEMATİK"] == mat_max]
yuksek_ort_isim=dframe[dframe["ORTALAMA"] > 70]["ÖĞRENCİ"]
bolum_ortalamalari = dframe.groupby('BÖLÜM')[["MATEMATİK", "FİZİK", "KİMYA"]].mean()

print("Fizik Dersi Ortalaması :", ort_fiz)
print("Matematik Dersi Ortalaması :", ort_mat)
print("Kimya Dersi Ortalaması :", ort_kim)
print("En yüksek matematik notunu alan öğrenci:")
print(ogrenci[["ÖĞRENCİ", "MATEMATİK"]])
print("Ortalaması 70'den Yüksek Öğrenciler\n",yuksek_ort_isim.tolist())
print("Bölüm Ortalamaları\n", bolum_ortalamalari)

Fizik Dersi Ortalaması : 71.0
Matematik Dersi Ortalaması : 71.0
Kimya Dersi Ortalaması : 79.0
En yüksek matematik notunu alan öğrenci:
  ÖĞRENCİ  MATEMATİK
3  Zeynep         90
Ortalaması 70'den Yüksek Öğrenciler
 ['Ali', 'Ayşe', 'Mehmet', 'Zeynep']
Bölüm Ortalamaları
             MATEMATİK  FİZİK  KİMYA
BÖLÜM                              
Bilgisayar       80.0   75.0   87.5
Fizik            57.5   67.5   77.5
Kimya            80.0   70.0   65.0
