In [1]:
import numpy as np

In [2]:
# SORU 1- LİSTE METODLARI 

notes = [85, 92, 76, 92, 100, 76, 85, 92]
unique_notes = list(set(notes))
max_number = max(unique_notes)
min_number = min(unique_notes)
serial_notes = sorted(unique_notes)
print("Benzersiz notlar:", unique_notes)
print("En yüksek not:", max_number)
print("En düşük not:", min_number)
print("Küçükten büyüğe sıralı notlar:", serial_notes)

Benzersiz notlar: [100, 92, 85, 76]
En yüksek not: 100
En düşük not: 76
Küçükten büyüğe sıralı notlar: [76, 85, 92, 100]


In [3]:
# SORU 2- SAYILAR

def armstrong(sayi):
    return sayi == sum(int(d) ** len(str(sayi)) for d in str(sayi))   #Sayıyı str olarak çevirdik her basamğını ayrı ayrı işlemek için 
    
sayi = 45
print(f"{sayi} bir Armstrong sayısıdır." if armstrong(sayi) else f"{sayi}  Armstrong sayısı değildir.")

45  Armstrong sayısı değildir.


In [4]:
#SORU 3 - KÜMELER

A = {"Python", "R", "SQL", "Java"}
B = {"C++", "Python", "JavaScript", "SQL"}

ortak = A.intersection(B)
sadece_a = A.difference(B)

A = np.array(["Python", "R", "SQL", "Java"])
B = np.array(["C++", "Python", "JavaScript", "SQL"])
birleşim = np.union1d(A,B)


print("Ortak diller : ",ortak)
print("Sadece A'da olanlar : ",sadece_a)
print("Birleşimi : ",birleşim)

Ortak diller :  {'SQL', 'Python'}
Sadece A'da olanlar :  {'R', 'Java'}
Birleşimi :  ['C++' 'Java' 'JavaScript' 'Python' 'R' 'SQL']


In [5]:
#SORU 4 - MODÜLLER

a=np.random.randint(1,100,10)
sayilar=np.array(a)
ortalama = sayilar.mean()
print("Random sayılar :", sayilar)
print("Sayıların Ortalaması : ",ortalama)

Random sayılar : [91 91 75 50 29 87 49 38 70 57]
Sayıların Ortalaması :  63.7


In [6]:
#SORU 5 - FONKSİYONLAR



def kelime_sayaci(metin):
  
    kelimeler = np.array(metin.split())
  
    toplam_kelime = kelimeler.size

    en_uzun = kelimeler[np.vectorize(len)(kelimeler).argmax()]
    
    uniq, counts = np.unique(kelimeler, return_counts=True)
    en_cok = uniq[counts.argmax()]
    
    return toplam_kelime, en_uzun, en_cok

metin = "Fenerbahçenin on numaralı oyuncusu John Duran,bu sezon  on gol on asist yapmıştır"
toplam, en_uzun_kelime, en_cok_kelime = kelime_sayaci(metin)

print("Toplam kelime sayısı:", toplam)
print("En uzun kelime:", en_uzun_kelime)
print("En sık geçen kelime:", en_cok_kelime)

Toplam kelime sayısı: 12
En uzun kelime: Fenerbahçenin
En sık geçen kelime: on


In [7]:
#SORU 6- GÖMÜLÜ FONKSİYONLAR
sayilar = [5, 12, 7, 18, 24, 3, 16]

sonuc = sorted(
    map(lambda x: x**2, filter(lambda x: x % 2 == 0, sayilar)),
    reverse=True
)
print(sonuc)

[576, 324, 256, 144]


In [8]:
#SORU 7- LAMBDA İFADELERİ
kelimeler =["veri", "bilim", "analiz", "yapayzeka", "python"]
uzunluk_siralama=sorted(kelimeler, key=lambda x: len(x))
uzunluk_siralama                      

['veri', 'bilim', 'analiz', 'python', 'yapayzeka']

In [9]:
#SORU 8 - METODLAR
def rakam_toplami(metin):
    return sum(int(mt) for mt in metin if mt.isdigit())

# Örnek kullanım
s = "abc12def3"
print(rakam_toplami(s))

6


In [10]:
#SORU  9-(EKSTRA) NUMPY 1 
list1=np.random.randint(0,51,10)
ortalama=np.mean(list1)
standart_sapma=np.std(list1)
buyuk_deger=np.max(list1)
print("Dizi:" , list1)
print("Ortalaması : ",ortalama)
print("Standart Spması : ",standart_sapma)
print("En Büyük Değeri :",buyuk_deger)

Dizi: [37 21 46 49 11  6 47 48  9 15]
Ortalaması :  28.9
Standart Spması :  17.178183838811368
En Büyük Değeri : 49


In [11]:
#SORU 10 - -(EKSTRA) NUMPY 2
matris = np.random.rand(5, 5)
sutun_ort = np.mean(matris, axis=0)
binary_matris = (matris > 0.5).astype(int)
print("Liste :",matris)
print("Sütunların Ortalaması :",sutun_ort)
print("Binary Matris:",binary_matris)

Liste : [[0.93817442 0.88421239 0.02763002 0.94614934 0.14644481]
 [0.85339163 0.52566015 0.85454019 0.87462336 0.2478571 ]
 [0.01224397 0.73364632 0.80510628 0.90523163 0.69060809]
 [0.71250871 0.80769413 0.26448995 0.87698663 0.56853571]
 [0.06099887 0.62840322 0.02954645 0.57598265 0.06905795]]
Sütunların Ortalaması : [0.51546352 0.71592324 0.39626258 0.83579472 0.34450073]
Binary Matris: [[1 1 0 1 0]
 [1 1 1 1 0]
 [0 1 1 1 1]
 [1 1 0 1 1]
 [0 1 0 1 0]]


In [14]:
#PROJE – “Kitap Satış Analiz Sistemi”

kitaplar = [
    {"isim": "Veri Bilimi 101", "yazar": "Ali", "tur": "Bilim", "satis": 1200, "yil": 2021},
    {"isim": "Python ile Yapay Zeka", "yazar": "Ayşe", "tur": "Bilim", "satis": 950, "yil": 2020},
    {"isim": "İstatistik Temelleri", "yazar": "Ali", "tur": "Akademik", "satis": 700, "yil": 2019},
    {"isim": "Makine Öğrenmesi", "yazar": "Can", "tur": "Bilim", "satis": 1800, "yil": 2022},
    {"isim": "Veri Görselleştirme", "yazar": "Deniz", "tur": "Sanat", "satis": 400, "yil": 2018},
    {"isim": "Matematiksel Modelleme", "yazar": "Ali", "tur": "Akademik", "satis": 1500, "yil": 2021},
    {"isim": "Bilgi Toplumu", "yazar": "Ayşe", "tur": "Sosyal", "satis": 600, "yil": 2022}
]

def en_cok_satan(kitaplar):
    return max(kitaplar, key=lambda x: x["satis"])

def yazar_satislari(kitaplar):
    sonuc = {}
    for k in kitaplar:
        sonuc[k["yazar"]] = sonuc.get(k["yazar"], 0) + k["satis"]
    return sonuc
turler = {k["tur"] for k in kitaplar}
populer_kitaplar = [k["isim"] for k in kitaplar if k["satis"] > 1000]
yeni_kitaplar = list(filter(lambda k: k["yil"] > 2020, kitaplar))
artirilmis_satis = list(map(lambda k: k["satis"] * 1.1, kitaplar))
sirali_kitaplar = sorted(kitaplar, key=lambda x: x["satis"], reverse=True)


print("En Çok Satan Kitap:", en_cok_satan(kitaplar))
print("Yazar Satışları:", yazar_satislari(kitaplar))
print("Kitap Türleri:", turler)
print("Popüler Kitaplar:", populer_kitaplar)
print("2020 Sonrası Kitaplar:", yeni_kitaplar)
print("%10 Artırılmış Satışlar:", artirilmis_satis)
print("nSatışa Göre Sıralı Kitaplar:", sirali_kitaplar)



En Çok Satan Kitap: {'isim': 'Makine Öğrenmesi', 'yazar': 'Can', 'tur': 'Bilim', 'satis': 1800, 'yil': 2022}
Yazar Satışları: {'Ali': 3400, 'Ayşe': 1550, 'Can': 1800, 'Deniz': 400}
Kitap Türleri: {'Akademik', 'Sanat', 'Bilim', 'Sosyal'}
Popüler Kitaplar: ['Veri Bilimi 101', 'Makine Öğrenmesi', 'Matematiksel Modelleme']
2020 Sonrası Kitaplar: [{'isim': 'Veri Bilimi 101', 'yazar': 'Ali', 'tur': 'Bilim', 'satis': 1200, 'yil': 2021}, {'isim': 'Makine Öğrenmesi', 'yazar': 'Can', 'tur': 'Bilim', 'satis': 1800, 'yil': 2022}, {'isim': 'Matematiksel Modelleme', 'yazar': 'Ali', 'tur': 'Akademik', 'satis': 1500, 'yil': 2021}, {'isim': 'Bilgi Toplumu', 'yazar': 'Ayşe', 'tur': 'Sosyal', 'satis': 600, 'yil': 2022}]
%10 Artırılmış Satışlar: [1320.0, 1045.0, 770.0000000000001, 1980.0000000000002, 440.00000000000006, 1650.0000000000002, 660.0]
nSatışa Göre Sıralı Kitaplar: [{'isim': 'Makine Öğrenmesi', 'yazar': 'Can', 'tur': 'Bilim', 'satis': 1800, 'yil': 2022}, {'isim': 'Matematiksel Modelleme', 'yaza